VERBS = [
    {"level": 1, "infinitive": "être", "meaning": "to be"},
    {"level": 1, "infinitive": "avoir", "meaning": "to have"},
    {"level": 1, "infinitive": "aller", "meaning": "to go"},
    {"level": 1, "infinitive": "faire", "meaning": "to do/make"},
    {"level": 1, "infinitive": "vouloir", "meaning": "to want"},
    {"level": 2, "infinitive": "pouvoir", "meaning": "to be able to/can"},
    {"level": 2, "infinitive": "devoir", "meaning": "must/have to"},
    {"level": 2, "infinitive": "savoir", "meaning": "to know how/to know facts"},
    {"level": 2, "infinitive": "connaître", "meaning": "to know/be familiar with"},
    {"level": 2, "infinitive": "dire", "meaning": "to say/tell"},
    {"level": 3, "infinitive": "voir", "meaning": "to see"},
    {"level": 3, "infinitive": "venir", "meaning": "to come"},
    {"level": 3, "infinitive": "prendre", "meaning": "to take"},
    {"level": 3, "infinitive": "mettre", "meaning": "to put"},
    {"level": 3, "infinitive": "donner", "meaning": "to give"},
    {"level": 4, "infinitive": "demander", "meaning": "to ask"},
    {"level": 4, "infinitive": "parler", "meaning": "to speak"},
    {"level": 4, "infinitive": "aimer", "meaning": "to like/love"},
    {"level": 4, "infinitive": "penser", "meaning": "to think"},
    {"level": 4, "infinitive": "comprendre", "meaning": "to understand"},
]


def c(id, level, verb, meaning, tense, prompt, answer, full_sentence, translation, note):
    return {
        "id": f"conjugation:{id}",
        "level": level,
        "verb": verb,
        "meaning": meaning,
        "tense": tense,
        "prompt": prompt,
        "answer": answer,
        "full_sentence": full_sentence,
        "translation": translation,
        "note": note,
    }


CONJUGATIONS = [
    c("etre-je-suis", 1, "être", "to be", "present", "Je ___ à la maison.", "suis", "Je suis à la maison.", "I am at home.", "être is irregular: je suis."),
    c("etre-infinitive-aller", 1, "être", "to be", "near future / infinitive", "Tu vas ___ en retard.", "être", "Tu vas être en retard.", "You are going to be late.", "After aller, use the infinitive."),
    c("etre-past-participle", 1, "être", "to be", "passé composé", "Il a ___ malade hier.", "été", "Il a été malade hier.", "He was sick yesterday.", "The past participle of être is été."),
    c("etre-nous-sommes", 1, "être", "to be", "present", "Nous ___ prêts.", "sommes", "Nous sommes prêts.", "We are ready.", "être is irregular: nous sommes."),
    c("etre-infinitive-voudrait", 1, "être", "to be", "infinitive after vouloir", "Elle voudrait ___ tranquille.", "être", "Elle voudrait être tranquille.", "She would like to be quiet.", "After voudrait, use the infinitive."),

    c("avoir-j-ai", 1, "avoir", "to have", "present", "J’___ un billet.", "ai", "J’ai un billet.", "I have a ticket.", "avoir is irregular: j’ai."),
    c("avoir-infinitive-aller", 1, "avoir", "to have", "near future / infinitive", "Tu vas ___ besoin d’aide.", "avoir", "Tu vas avoir besoin d’aide.", "You are going to need help.", "After aller, use the infinitive."),
    c("avoir-past-participle", 1, "avoir", "to have", "passé composé", "Elle a ___ peur.", "eu", "Elle a eu peur.", "She was scared.", "The past participle of avoir is eu."),
    c("avoir-nous-avons", 1, "avoir", "to have", "present", "Nous ___ le temps.", "avons", "Nous avons le temps.", "We have time.", "avoir is irregular: nous avons."),
    c("avoir-infinitive-voudriez", 1, "avoir", "to have", "infinitive after vouloir", "Vous voudriez ___ une table près de la fenêtre ?", "avoir", "Vous voudriez avoir une table près de la fenêtre ?", "Would you like to have a table near the window?", "After voudriez, use the infinitive."),

    c("aller-je-vais", 1, "aller", "to go", "present", "Je ___ au marché.", "vais", "Je vais au marché.", "I am going to the market.", "aller is irregular: je vais."),
    c("aller-infinitive-pouvoir", 1, "aller", "to go", "infinitive after pouvoir", "Tu peux ___ maintenant.", "aller", "Tu peux aller maintenant.", "You can go now.", "After peux, use the infinitive."),
    c("aller-past-participle", 1, "aller", "to go", "passé composé", "Elle est ___ à Lyon.", "allée", "Elle est allée à Lyon.", "She went to Lyon.", "aller uses être in the passé composé; allée agrees with elle."),
    c("aller-nous-allons", 1, "aller", "to go", "present", "Nous ___ au cinéma.", "allons", "Nous allons au cinéma.", "We are going to the movies.", "aller is irregular: nous allons."),
    c("aller-vous-allez", 1, "aller", "to go", "present", "Vous ___ où ?", "allez", "Vous allez où ?", "Where are you going?", "aller is irregular: vous allez."),

    c("faire-je-fais", 1, "faire", "to do/make", "present", "Je ___ mes devoirs.", "fais", "Je fais mes devoirs.", "I am doing my homework.", "faire is irregular: je fais."),
    c("faire-infinitive-aller", 1, "faire", "to do/make", "near future / infinitive", "Tu vas ___ le dîner ?", "faire", "Tu vas faire le dîner ?", "Are you going to make dinner?", "After aller, use the infinitive."),
    c("faire-past-participle", 1, "faire", "to do/make", "passé composé", "Elle a ___ une erreur.", "fait", "Elle a fait une erreur.", "She made a mistake.", "The past participle of faire is fait."),
    c("faire-nous-faisons", 1, "faire", "to do/make", "present", "Nous ___ une pause.", "faisons", "Nous faisons une pause.", "We are taking a break.", "In faisons, ai is pronounced like a schwa."),
    c("faire-vous-faites", 1, "faire", "to do/make", "present", "Vous ___ quoi ce soir ?", "faites", "Vous faites quoi ce soir ?", "What are you doing tonight?", "faire is irregular: vous faites."),

    c("vouloir-je-veux", 1, "vouloir", "to want", "present", "Je ___ un café.", "veux", "Je veux un café.", "I want a coffee.", "vouloir is irregular: je veux."),
    c("vouloir-conditional-politeness", 1, "vouloir", "to want", "conditional / polite", "Je ___ prendre un café.", "voudrais", "Je voudrais prendre un café.", "I would like to have a coffee.", "Je voudrais is a polite way to say I would like."),
    c("vouloir-past-participle", 1, "vouloir", "to want", "passé composé", "Elle a ___ changer de place.", "voulu", "Elle a voulu changer de place.", "She wanted to change seats.", "The past participle of vouloir is voulu."),
    c("vouloir-nous-voulons", 1, "vouloir", "to want", "present", "Nous ___ comprendre.", "voulons", "Nous voulons comprendre.", "We want to understand.", "vouloir is irregular: nous voulons."),
    c("vouloir-vous-voulez", 1, "vouloir", "to want", "present", "Vous ___ venir avec nous ?", "voulez", "Vous voulez venir avec nous ?", "Do you want to come with us?", "vouloir is irregular: vous voulez."),

    c("pouvoir-je-peux", 2, "pouvoir", "to be able to/can", "present", "Je ___ vous aider.", "peux", "Je peux vous aider.", "I can help you.", "pouvoir is irregular: je peux."),
    c("pouvoir-infinitive-aller", 2, "pouvoir", "to be able to/can", "near future / infinitive", "Tu vas ___ venir demain ?", "pouvoir", "Tu vas pouvoir venir demain ?", "Will you be able to come tomorrow?", "After aller, use the infinitive."),
    c("pouvoir-past-participle", 2, "pouvoir", "to be able to/can", "passé composé", "Elle a ___ finir à temps.", "pu", "Elle a pu finir à temps.", "She was able to finish on time.", "The past participle of pouvoir is pu."),
    c("pouvoir-nous-pouvons", 2, "pouvoir", "to be able to/can", "present", "Nous ___ payer par carte.", "pouvons", "Nous pouvons payer par carte.", "We can pay by card.", "pouvoir is irregular: nous pouvons."),
    c("pouvoir-vous-pouvez", 2, "pouvoir", "to be able to/can", "present", "Vous ___ répéter ?", "pouvez", "Vous pouvez répéter ?", "Can you repeat?", "pouvoir is irregular: vous pouvez."),

    c("devoir-je-dois", 2, "devoir", "must/have to", "present", "Je ___ partir maintenant.", "dois", "Je dois partir maintenant.", "I have to leave now.", "devoir is irregular: je dois."),
    c("devoir-infinitive-aller", 2, "devoir", "must/have to", "near future / infinitive", "Tu vas ___ attendre ici.", "devoir", "Tu vas devoir attendre ici.", "You are going to have to wait here.", "After aller, use the infinitive."),
    c("devoir-past-participle", 2, "devoir", "must/have to", "passé composé", "Il a ___ annuler.", "dû", "Il a dû annuler.", "He had to cancel.", "The past participle of devoir is dû."),
    c("devoir-nous-devons", 2, "devoir", "must/have to", "present", "Nous ___ prendre le train.", "devons", "Nous devons prendre le train.", "We have to take the train.", "devoir is irregular: nous devons."),
    c("devoir-vous-devez", 2, "devoir", "must/have to", "present", "Vous ___ signer ici.", "devez", "Vous devez signer ici.", "You have to sign here.", "devoir is irregular: vous devez."),

    c("savoir-je-sais", 2, "savoir", "to know how/to know facts", "present", "Je ___ nager.", "sais", "Je sais nager.", "I know how to swim.", "savoir is irregular: je sais."),
    c("savoir-infinitive-aller", 2, "savoir", "to know how/to know facts", "near future / infinitive", "Tu vas ___ la réponse bientôt.", "savoir", "Tu vas savoir la réponse bientôt.", "You are going to know the answer soon.", "After aller, use the infinitive."),
    c("savoir-past-participle", 2, "savoir", "to know how/to know facts", "passé composé", "Elle a ___ son nom tout de suite.", "su", "Elle a su son nom tout de suite.", "She knew his name right away.", "The past participle of savoir is su."),
    c("savoir-nous-savons", 2, "savoir", "to know how/to know facts", "present", "Nous ___ où aller.", "savons", "Nous savons où aller.", "We know where to go.", "savoir is irregular: nous savons."),
    c("savoir-vous-savez", 2, "savoir", "to know how/to know facts", "present", "Vous ___ parler français ?", "savez", "Vous savez parler français ?", "Do you know how to speak French?", "savoir is irregular: vous savez."),

    c("connaitre-je-connais", 2, "connaître", "to know/be familiar with", "present", "Je ___ ce quartier.", "connais", "Je connais ce quartier.", "I know this neighborhood.", "connaître is for familiarity with people/places/things."),
    c("connaitre-infinitive-aller", 2, "connaître", "to know/be familiar with", "near future / infinitive", "Tu vas ___ mes amis ce soir.", "connaître", "Tu vas connaître mes amis ce soir.", "You are going to meet/get to know my friends tonight.", "After aller, use the infinitive."),
    c("connaitre-past-participle", 2, "connaître", "to know/be familiar with", "passé composé", "Elle a ___ Paul à Paris.", "connu", "Elle a connu Paul à Paris.", "She met/knew Paul in Paris.", "The past participle of connaître is connu."),
    c("connaitre-nous-connaissons", 2, "connaître", "to know/be familiar with", "present", "Nous ___ bien cette chanson.", "connaissons", "Nous connaissons bien cette chanson.", "We know this song well.", "The nous form keeps the double s sound: connaissons."),
    c("connaitre-vous-connaissez", 2, "connaître", "to know/be familiar with", "present", "Vous ___ ce restaurant ?", "connaissez", "Vous connaissez ce restaurant ?", "Do you know this restaurant?", "Use connaître for familiarity."),

    c("dire-je-dis", 2, "dire", "to say/tell", "present", "Je ___ la vérité.", "dis", "Je dis la vérité.", "I tell the truth.", "dire is irregular: je dis."),
    c("dire-infinitive-aller", 2, "dire", "to say/tell", "near future / infinitive", "Tu vas ___ bonjour à Marie.", "dire", "Tu vas dire bonjour à Marie.", "You are going to say hello to Marie.", "After aller, use the infinitive."),
    c("dire-past-participle", 2, "dire", "to say/tell", "passé composé", "Elle a ___ merci.", "dit", "Elle a dit merci.", "She said thank you.", "The past participle of dire is dit."),
    c("dire-nous-disons", 2, "dire", "to say/tell", "present", "Nous ___ toujours la même chose.", "disons", "Nous disons toujours la même chose.", "We always say the same thing.", "dire is irregular: nous disons."),
    c("dire-vous-dites", 2, "dire", "to say/tell", "present", "Vous ___ quoi ?", "dites", "Vous dites quoi ?", "What are you saying?", "dire is irregular: vous dites."),

    c("voir-je-vois", 3, "voir", "to see", "present", "Je ___ la gare.", "vois", "Je vois la gare.", "I see the train station.", "voir is irregular: je vois."),
    c("voir-infinitive-aller", 3, "voir", "to see", "near future / infinitive", "Tu vas ___ le film ce soir.", "voir", "Tu vas voir le film ce soir.", "You are going to see the movie tonight.", "After aller, use the infinitive."),
    c("voir-past-participle", 3, "voir", "to see", "passé composé", "Elle a ___ la Tour Eiffel.", "vu", "Elle a vu la Tour Eiffel.", "She saw the Eiffel Tower.", "The past participle of voir is vu."),
    c("voir-nous-voyons", 3, "voir", "to see", "present", "Nous ___ le problème.", "voyons", "Nous voyons le problème.", "We see the problem.", "voir is irregular: nous voyons."),
    c("voir-vous-voyez", 3, "voir", "to see", "present", "Vous ___ la sortie ?", "voyez", "Vous voyez la sortie ?", "Do you see the exit?", "voir is irregular: vous voyez."),

    c("venir-je-viens", 3, "venir", "to come", "present", "Je ___ avec toi.", "viens", "Je viens avec toi.", "I am coming with you.", "venir is irregular: je viens."),
    c("venir-infinitive-aller", 3, "venir", "to come", "near future / infinitive", "Tu vas ___ demain ?", "venir", "Tu vas venir demain ?", "Are you going to come tomorrow?", "After aller, use the infinitive."),
    c("venir-past-participle", 3, "venir", "to come", "passé composé", "Elle est ___ en métro.", "venue", "Elle est venue en métro.", "She came by metro.", "venir uses être in the passé composé; venue agrees with elle."),
    c("venir-nous-venons", 3, "venir", "to come", "present", "Nous ___ de Montréal.", "venons", "Nous venons de Montréal.", "We come from Montreal.", "venir is irregular: nous venons."),
    c("venir-vous-venez", 3, "venir", "to come", "present", "Vous ___ souvent ici ?", "venez", "Vous venez souvent ici ?", "Do you come here often?", "venir is irregular: vous venez."),

    c("prendre-je-prends", 3, "prendre", "to take", "present", "Je ___ le métro.", "prends", "Je prends le métro.", "I take the metro.", "prendre is irregular: je prends."),
    c("prendre-infinitive-aller", 3, "prendre", "to take", "near future / infinitive", "Je vais ___ rendez-vous.", "prendre", "Je vais prendre rendez-vous.", "I am going to make an appointment.", "After aller, use the infinitive."),
    c("prendre-past-participle", 3, "prendre", "to take", "passé composé", "J’ai ___ le mauvais train.", "pris", "J’ai pris le mauvais train.", "I took the wrong train.", "The past participle of prendre is pris."),
    c("prendre-infinitive-voudrais", 3, "prendre", "to take", "infinitive after vouloir", "Je voudrais ___ un café.", "prendre", "Je voudrais prendre un café.", "I would like to have a coffee.", "After voudrais, use the infinitive."),
    c("prendre-infinitive-pouvoir", 3, "prendre", "to take", "infinitive after pouvoir", "Vous pouvez ___ ma carte ?", "prendre", "Vous pouvez prendre ma carte ?", "Can you take my card?", "After pouvez, use the infinitive."),

    c("mettre-je-mets", 3, "mettre", "to put", "present", "Je ___ mon manteau.", "mets", "Je mets mon manteau.", "I put on my coat.", "mettre is irregular: je mets."),
    c("mettre-infinitive-aller", 3, "mettre", "to put", "near future / infinitive", "Tu vas ___ la table.", "mettre", "Tu vas mettre la table.", "You are going to set the table.", "After aller, use the infinitive."),
    c("mettre-past-participle", 3, "mettre", "to put", "passé composé", "Elle a ___ les clés dans son sac.", "mis", "Elle a mis les clés dans son sac.", "She put the keys in her bag.", "The past participle of mettre is mis."),
    c("mettre-nous-mettons", 3, "mettre", "to put", "present", "Nous ___ les livres ici.", "mettons", "Nous mettons les livres ici.", "We put the books here.", "mettre is irregular: nous mettons."),
    c("mettre-vous-mettez", 3, "mettre", "to put", "present", "Vous ___ votre nom ici.", "mettez", "Vous mettez votre nom ici.", "You put your name here.", "mettre is irregular: vous mettez."),

    c("donner-je-donne", 3, "donner", "to give", "present", "Je ___ mon numéro.", "donne", "Je donne mon numéro.", "I give my number.", "Regular -er verb: je donne."),
    c("donner-infinitive-aller", 3, "donner", "to give", "near future / infinitive", "Tu vas ___ ton adresse ?", "donner", "Tu vas donner ton adresse ?", "Are you going to give your address?", "After aller, use the infinitive."),
    c("donner-past-participle", 3, "donner", "to give", "passé composé", "Elle a ___ un conseil.", "donné", "Elle a donné un conseil.", "She gave some advice.", "Regular -er past participles end in -é."),
    c("donner-nous-donnons", 3, "donner", "to give", "present", "Nous ___ rendez-vous à huit heures.", "donnons", "Nous donnons rendez-vous à huit heures.", "We set a meeting for eight o’clock.", "Regular -er verb: nous donnons."),
    c("donner-vous-donnez", 3, "donner", "to give", "present", "Vous ___ la carte au serveur.", "donnez", "Vous donnez la carte au serveur.", "You give the card to the waiter.", "Regular -er verb: vous donnez."),

    c("demander-je-demande", 4, "demander", "to ask", "present", "Je ___ l’addition.", "demande", "Je demande l’addition.", "I ask for the check.", "demander can mean ask or ask for."),
    c("demander-infinitive-aller", 4, "demander", "to ask", "near future / infinitive", "Tu vas ___ ton chemin.", "demander", "Tu vas demander ton chemin.", "You are going to ask for directions.", "After aller, use the infinitive."),
    c("demander-past-participle", 4, "demander", "to ask", "passé composé", "Elle a ___ de l’aide.", "demandé", "Elle a demandé de l’aide.", "She asked for help.", "Regular -er past participles end in -é."),
    c("demander-nous-demandons", 4, "demander", "to ask", "present", "Nous ___ une table pour deux.", "demandons", "Nous demandons une table pour deux.", "We ask for a table for two.", "Regular -er verb: nous demandons."),
    c("demander-vous-demandez", 4, "demander", "to ask", "present", "Vous ___ pourquoi ?", "demandez", "Vous demandez pourquoi ?", "You ask why?", "Regular -er verb: vous demandez."),

    c("parler-je-parle", 4, "parler", "to speak", "present", "Je ___ un peu français.", "parle", "Je parle un peu français.", "I speak a little French.", "Regular -er verb: je parle."),
    c("parler-infinitive-aller", 4, "parler", "to speak", "near future / infinitive", "Tu vas ___ avec le professeur.", "parler", "Tu vas parler avec le professeur.", "You are going to speak with the teacher.", "After aller, use the infinitive."),
    c("parler-past-participle", 4, "parler", "to speak", "passé composé", "Elle a ___ trop vite.", "parlé", "Elle a parlé trop vite.", "She spoke too quickly.", "Regular -er past participles end in -é."),
    c("parler-nous-parlons", 4, "parler", "to speak", "present", "Nous ___ de nos vacances.", "parlons", "Nous parlons de nos vacances.", "We are talking about our vacation.", "Regular -er verb: nous parlons."),
    c("parler-vous-parlez", 4, "parler", "to speak", "present", "Vous ___ anglais ?", "parlez", "Vous parlez anglais ?", "Do you speak English?", "Regular -er verb: vous parlez."),

    c("aimer-j-aime", 4, "aimer", "to like/love", "present", "J’___ ce livre.", "aime", "J’aime ce livre.", "I like this book.", "Use j’ before a vowel sound."),
    c("aimer-infinitive-aller", 4, "aimer", "to like/love", "near future / infinitive", "Tu vas ___ ce café.", "aimer", "Tu vas aimer ce café.", "You are going to like this café.", "After aller, use the infinitive."),
    c("aimer-past-participle", 4, "aimer", "to like/love", "passé composé", "Elle a ___ le film.", "aimé", "Elle a aimé le film.", "She liked the movie.", "Regular -er past participles end in -é."),
    c("aimer-nous-aimons", 4, "aimer", "to like/love", "present", "Nous ___ marcher le soir.", "aimons", "Nous aimons marcher le soir.", "We like walking in the evening.", "Regular -er verb: nous aimons."),
    c("aimer-vous-aimez", 4, "aimer", "to like/love", "present", "Vous ___ la musique ?", "aimez", "Vous aimez la musique ?", "Do you like music?", "Regular -er verb: vous aimez."),

    c("penser-je-pense", 4, "penser", "to think", "present", "Je ___ à ma famille.", "pense", "Je pense à ma famille.", "I think about my family.", "penser à means to think about."),
    c("penser-infinitive-aller", 4, "penser", "to think", "near future / infinitive", "Tu vas ___ à moi ?", "penser", "Tu vas penser à moi ?", "Are you going to think of me?", "After aller, use the infinitive."),
    c("penser-past-participle", 4, "penser", "to think", "passé composé", "Elle a ___ à fermer la porte.", "pensé", "Elle a pensé à fermer la porte.", "She remembered to close the door.", "penser à + infinitive can mean remember to do something."),
    c("penser-nous-pensons", 4, "penser", "to think", "present", "Nous ___ que c’est possible.", "pensons", "Nous pensons que c’est possible.", "We think it is possible.", "Regular -er verb: nous pensons."),
    c("penser-vous-pensez", 4, "penser", "to think", "present", "Vous ___ quoi de ce musée ?", "pensez", "Vous pensez quoi de ce musée ?", "What do you think of this museum?", "Regular -er verb: vous pensez."),

    c("comprendre-je-comprends", 4, "comprendre", "to understand", "present", "Je ___ la question.", "comprends", "Je comprends la question.", "I understand the question.", "comprendre follows prendre: je comprends."),
    c("comprendre-infinitive-aller", 4, "comprendre", "to understand", "near future / infinitive", "Tu vas ___ bientôt.", "comprendre", "Tu vas comprendre bientôt.", "You are going to understand soon.", "After aller, use the infinitive."),
    c("comprendre-past-participle", 4, "comprendre", "to understand", "passé composé", "Elle a ___ l’exercice.", "compris", "Elle a compris l’exercice.", "She understood the exercise.", "The past participle of comprendre is compris."),
    c("comprendre-nous-comprenons", 4, "comprendre", "to understand", "present", "Nous ___ le problème.", "comprenons", "Nous comprenons le problème.", "We understand the problem.", "comprendre is irregular: nous comprenons."),
    c("comprendre-vous-comprenez", 4, "comprendre", "to understand", "present", "Vous ___ ce que je dis ?", "comprenez", "Vous comprenez ce que je dis ?", "Do you understand what I am saying?", "comprendre is irregular: vous comprenez."),
]
